language: python
# ===== Linux ======
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
matrix:
  include:     
    # ======= OSX ======== 
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install -U pip
        - pip3 install -r requirements.txt
        - pip3 install -r requirements-test.txt
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install -U pip
        - pip3 install -r requirements.txt
        - pip3 install -r requirements-test.txt
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    - name: "Latest Xcode version build"
      os: osx
      osx_image: xcode12.2  # Python ?.?.? running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install -U pip
        - pip3 install -r requirements.txt
        - pip3 install -r requirements-test.txt
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    #  ====== WINDOWS =========
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
        - python -m pip install -r requirements.txt
        - python -m pip install -r requirements-test.txt
        - python -m pip install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: python -m pytest
before_install:
  - python -m pip install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-test.txt
  - pip3 install codecov
script: pytest
after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always